version: '3'
services:
  postgres:
    ports:
      - ${HOST_POSTGRES_PORT}:${POSTGRES_PORT}
  postgraphile:
    build: postgraphile
    volumes:
      - ./postgraphile:/usr/relay-modern-boilerplate/postgraphile
    ports:
      - ${HOST_POSTGRAPHILE_PORT}:${POSTGRAPHILE_PORT}
    command: /bin/bash -c "npm i && npm run start"
  app:
    build: app
    volumes:
      - ./app:/usr/relay-modern-boilerplate/app
      - ./app/node_modules:/usr/relay-modern-boilerplate/node_modules:cached
    ports:
      - ${HOST_APP_PORT}:${APP_PORT}
    command: /bin/bash -c "npm i && npm run build:dll && npm run dev"
