version: '3'
volumes:
  postgres-data:
    driver: 'local'
networks:
  private:
    driver: 'bridge'
  public:
    driver: 'bridge'
services:
  postgres:
    image: postgres
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - private
    ports:
      - 5432:5432
  postgraphile:
    image: relay-modern-boilerplate/postgraphile
    env_file: .env
    environment:
      - NO_AUTH=false
    working_dir: /usr/src/postgraphile
    restart: always
    depends_on:
      - postgres
    networks:
      - private
      - public
